### ISSUE TITLE
build error with exit code 1

### ISSUE THREAD

**Issue by sethupsanil** [Red-Folder/bgs-core#77]
D:\xamp\htdocs\phonegap\backbutton>phonegap platform add android
Adding android project...

Creating Cordova project for the Android platform:

        Path: platforms\android
        Package: com.phonegap.helloworld
        Name: Back_Button
        Activity: MainActivity
        Android target: android-24

Subproject Path: CordovaLib

Android project created with cordova-android@6.0.0

Installing "com.red_folder.phonegap.plugin.backgroundservice" for android

ANDROID_HOME=C:\Users\sethu\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files (x86)\Java\jdk1.8.0_11

Subproject Path: CordovaLib

Starting a new Gradle Daemon for this build (subsequent builds will be faster).

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/
2.14.1/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

Failed to install 'com.red_folder.phonegap.plugin.backgroundservice':Error: cmd:
 Command failed with exit code 1
    at ChildProcess.whenDone (D:\xamp\htdocs\phonegap\backbutton\platforms\andro
id\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

Error: cmd: Command failed with exit code 1

**Comment by Red-Folder** [comment]
That reads to me as a Gradle error ... nothing to do with the plugin.

Follow the instructions in the error message to resolve
